<?php

$pdf_map = array(
    'USD' => '&#36;?',
    'CAD' => '&#36;?',
    'GBP' => '&#163;?',
    'EUR' => '&#8364;?',
    'AUD' => '&#36;',
    'ARS' => '&#36;',
    'BRL' => 'R&#36;',
    'CNY' => '&#165;?',
    'COP' => '&#36;',
    'HRK' => 'kn',
    'CZK' => 'Kc',
    'DKK' => 'kr',
    'HKD' => '&#36;',
    'INR' => 'Rs',
    'IDR' => 'Rp',
    'JPY' => '&#165;',
    'LTL' => 'Lt',
    'MYR' => 'RM',
    'MUR' => 'Rs',
    'MXN' => '&#36;',
    'NZD' => '&#36;',
    'NOK' => 'kr',
    'PKR' => 'Rs',
    'PLN' => 'zl',
    'SAR' => 'SR',
    'SGD' => '&#36;',
    'ZAR' => 'R',
    'SEK' => 'kr',
    'CHF' => 'SFr',
    'TRY' => 'TL'
);
?>